### ISSUE TITLE
Refactor Event Register API

### ISSUE THREAD

**Issue by priyanshisharma** [ECellNitrr/ecell-main-server#12]
**Describe the issue**
We are improving the reliability and reusability of our code. Thereby, we need to simplify and document our code. Use good DRF practices taking <a href="https://github.com/ECellNitrr/teesco-backend">teesco-backend</a> as reference.

Navigate to `events/views.py` and refer `event_register` view and simplify it. Also write its swagger documentation.

**Expected behaviour**
Code must be understandable and reproducible.

**Comment by KunalAnkur** [comment]
taking this !
