### ISSUE TITLE
Test Get Mentors API

### ISSUE THREAD

**Issue by priyanshisharma** [ECellNitrr/ecell-main-server#22]
**Is your feature request related to a problem? Please describe.**
We need to test the Get Mentors API refactored in #15

**Describe the solution you'd like**
Relevant tests must be added to tests/mentors/tests_get_mentors_api.py

**Additional context**
Few suggestions for how the tests could be are as follows:
* Invalid Input (e.g. `twentynineteen`)
* Fetch empty mentor list
* Fetch list with multiple mentors
* etc.

**Comment by akhil-maker** [comment]
I would like to take this issue
