### ISSUE TITLE
Test Get Events API

### ISSUE THREAD

**Issue by priyanshisharma** [ECellNitrr/ecell-main-server#24]
**Is your feature request related to a problem? Please describe.**
We need to test the Get Events API refactored in #20 

**Describe the solution you'd like**
Relevant tests must be added to `tests/events/tests_get_events_api.py`.

**Additional context**
Few suggestions for how the tests could be are as follows:
* Invalid Input (e.g. `twentynineteen`)
* Fetch empty event list
* Fetch list with multiple events
* etc.

**Comment by akhil-maker** [comment]
I would like to take this issue
