### ISSUE TITLE
Test Register Event API

### ISSUE THREAD

**Issue by priyanshisharma** [ECellNitrr/ecell-main-server#25]
**Is your feature request related to a problem? Please describe.**
We need to test the Event Register API refactored in #23

**Describe the solution you'd like**
Relevant tests must be added to `tests/events/tests_events_register_api.py`.

**Additional context**
Few suggestions for how the tests could be are as follows:
* Invalid Input (e.g. `twentynineteen`)
* Unauthorised User
* Re-Registration
* Unverified User
* etc.

**Comment by KunalAnkur** [comment]
Taking this
