### ISSUE TITLE
Add swagger docs support

### ISSUE THREAD

**Issue by priyanshisharma** [ECellNitrr/ecell-main-server#3]
**Is your feature request related to a problem? Please describe.**
It is great to have all API docs in one place. Especially if it is interactive and provides examples on response, request body etc.,

**Describe the solution you'd like**
Integrate swagger docs into the django server with help of django-yasg package.

**Additional context**
One may refer the <a href="https://github.com/ECellNitrr/teesco-backend/pull/53">PR made in teesco-backend</a> for adding swagger docs, if required.

**Comment by sahil9001** [comment]
Taking this!

**Comment by KunalAnkur** [comment]
I am working on this

**Comment by sahil9001** [comment]
I claimed the issue first
