### ISSUE TITLE
Add Testcases for Registration 

### ISSUE THREAD

**Issue by anshsrtv** [ECellNitrr/ecell-main-server#8]
**Is your feature request related to a problem? Please describe.**

Taking [Teesco Backend](https://github.com/ECellNitrr/teesco-backend/) as a reference, test the User Registration API.

**Describe the solution you'd like**

Create a file in `/tests/users` named `tests_register_api.py` and create testcases for the API.

**Additional context**

https://github.com/ECellNitrr/teesco-backend/blob/dev/tests/users/tests_register_api.py

**Comment by akhil-maker** [comment]
I would like to take this issue
