### ISSUE TITLE
Add testcases for Login API

### ISSUE THREAD

**Issue by anshsrtv** [ECellNitrr/ecell-main-server#9]
**Is your feature request related to a problem? Please describe.**

Taking [Teesco Backend](https://github.com/ECellNitrr/teesco-backend/) as a reference, test the User Login API.

**Describe the solution you'd like**

Create a file in `/tests/users/` named `tests_login_api.py` and create testcases for the API.

**Additional context**

https://github.com/ECellNitrr/teesco-backend/blob/dev/tests/users/tests_login_api.py

**Comment by anshsrtv** [comment]
@sahil9001 Should I assign it to you?

**Comment by sahil9001** [comment]
Yes sir taking this!
